#####################################
#      SHELL_COMMAND EXAMPLE        #
#####################################

## Save Input Settings

save_input_settings: 'python /home/homeassistant/.homeassistant/bin/hass_saved_settings.py -act update_settings -sec {{ section }} -set {{ settings }} -val "{{ value }}"'
# ex.  ''/home/mike/.homeassistant/shell_scripts/hass_settings/hass_saved_settings.py -sec {{ section }} -set {{ settings }} -val "{{ value }}"'

load_input_settings: 'python /home/homeassistant/.homeassistant/bin/hass_saved_settings.py -act update_hass'
# ex. '/home/mike/.homeassistant/shell_scripts/hass_settings/hass_saved_settings.py -act update_hass'