exclude:
  domains:
    - automation
    - weblink
    - updater
    - group
    - discovery
    - input_boolean
  entities:
    - sensor.since_last_boot
    - sensor.since_last_boot_templated
    - sensor.external_ip
    - sensor.time
    - sensor.date
    - sensor.netatmo_indoor_wifi
    - sensor.netatmo_master_bedroom_radio
    - sensor.netatmo_master_bedroom_battery
    - sensor.netatmo_other_battery
    - sensor.netatmo_other_radio
    - sensor.netatmo_outdoor_battery
    - sensor.netatmo_rain_battery
    - sensor.netatmo_rain_radio