exclude:
  domains:
    - automation
    - weblink
    - updater
    - group
    - discovery
    - zone
    - proximity
  entities:
    - sensor.since_last_boot
    - sensor.since_last_boot_templated
    - sensor.external_ip
    - sensor.time
    - sensor.date