- name: pushbullet
  platform: pushbullet
  api_key: !secret pushbullet_key

- platform: group
  name: iv_push
  services:
    - service: pushbullet
      data:
        target: !secret iv_pushbullet

- platform: group
  name: notify_ivan
  services:
    - service: iv_push

- platform: group
  name: notify_all
  services:
    - service: notify_ivan
    - service: html_push

- platform: html5
  name: html_push
  gcm_api_key: !secret gcm_api_key
  gcm_sender_id: !secret gcm_sender_id