- platform: apcupsd
  resources:
#    - hostname
#    - upsname
    - starttime
#    - model
    - status
    - linev
    - loadpct
    - bcharge
    - timeleft
    - mbattchg
    - mintimel
    - maxtime
    - sense
#    - lotrans
#    - hitrans
#    - alarmdel
#    - battv
    - lastxfer
    - numxfers
    - tonbatt
    - cumonbatt
    - xoffbatt
#    - selftest
#    - statflag
#    - serialno
#    - battdate
#    - nominv
#    - nombattv
#    - firmware