- alias: Going to bed

  trigger:
    - platform: state
      entity_id: input_boolean.bedtime
      state: 'on'
      for:
        hours: 0
        minutes: 5
        seconds: 0

  action:
    - service: script.turn_on
      entity_id: script.going_to_bed